// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: pkg/proto/gophkeeper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DataType represents the type of stored secret.
type DataType int32

const (
	DataType_DATA_TYPE_UNSPECIFIED    DataType = 0
	DataType_DATA_TYPE_LOGIN_PASSWORD DataType = 1
	DataType_DATA_TYPE_TEXT           DataType = 2
	DataType_DATA_TYPE_BINARY         DataType = 3
	DataType_DATA_TYPE_CARD           DataType = 4
)

// Enum value maps for DataType.
var (
	DataType_name = map[int32]string{
		0: "DATA_TYPE_UNSPECIFIED",
		1: "DATA_TYPE_LOGIN_PASSWORD",
		2: "DATA_TYPE_TEXT",
		3: "DATA_TYPE_BINARY",
		4: "DATA_TYPE_CARD",
	}
	DataType_value = map[string]int32{
		"DATA_TYPE_UNSPECIFIED":    0,
		"DATA_TYPE_LOGIN_PASSWORD": 1,
		"DATA_TYPE_TEXT":           2,
		"DATA_TYPE_BINARY":         3,
		"DATA_TYPE_CARD":           4,
	}
)

func (x DataType) Enum() *DataType {
	p := new(DataType)
	*p = x
	return p
}

func (x DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_gophkeeper_proto_enumTypes[0].Descriptor()
}

func (DataType) Type() protoreflect.EnumType {
	return &file_pkg_proto_gophkeeper_proto_enumTypes[0]
}

func (x DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DataType.Descriptor instead.
func (DataType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

// RegisterRequest contains user registration data.
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// RegisterResponse contains the result of registration.
type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// LoginRequest contains user authentication data.
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// LoginResponse contains the authentication result.
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix timestamp
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LoginResponse) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Secret represents an encrypted secret.
type Secret struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	DataType      DataType               `protobuf:"varint,4,opt,name=data_type,json=dataType,proto3,enum=gophkeeper.DataType" json:"data_type,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,5,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata      string                 `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	Deleted       bool                   `protobuf:"varint,10,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Secret) Reset() {
	*x = Secret{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Secret) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Secret) ProtoMessage() {}

func (x *Secret) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Secret.ProtoReflect.Descriptor instead.
func (*Secret) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{4}
}

func (x *Secret) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Secret) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Secret) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Secret) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *Secret) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *Secret) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Secret) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Secret) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Secret) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Secret) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// CreateSecretRequest contains data for creating a new secret.
type CreateSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DataType      DataType               `protobuf:"varint,2,opt,name=data_type,json=dataType,proto3,enum=gophkeeper.DataType" json:"data_type,omitempty"`
	EncryptedData []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata      string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretRequest) Reset() {
	*x = CreateSecretRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretRequest) ProtoMessage() {}

func (x *CreateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretRequest.ProtoReflect.Descriptor instead.
func (*CreateSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{5}
}

func (x *CreateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSecretRequest) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *CreateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *CreateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// CreateSecretResponse contains the created secret.
type CreateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSecretResponse) Reset() {
	*x = CreateSecretResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSecretResponse) ProtoMessage() {}

func (x *CreateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSecretResponse.ProtoReflect.Descriptor instead.
func (*CreateSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{6}
}

func (x *CreateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// GetSecretRequest contains the secret ID to retrieve.
type GetSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretRequest) Reset() {
	*x = GetSecretRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretRequest) ProtoMessage() {}

func (x *GetSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretRequest.ProtoReflect.Descriptor instead.
func (*GetSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{7}
}

func (x *GetSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetSecretResponse contains the requested secret.
type GetSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSecretResponse) Reset() {
	*x = GetSecretResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretResponse) ProtoMessage() {}

func (x *GetSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSecretResponse.ProtoReflect.Descriptor instead.
func (*GetSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{8}
}

func (x *GetSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// ListSecretsRequest contains optional filters for listing secrets.
type ListSecretsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataType      DataType               `protobuf:"varint,1,opt,name=data_type,json=dataType,proto3,enum=gophkeeper.DataType" json:"data_type,omitempty"` // Optional filter by type
	Since         int64                  `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`                                                // Optional: only return secrets modified after this timestamp
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsRequest) Reset() {
	*x = ListSecretsRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsRequest) ProtoMessage() {}

func (x *ListSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsRequest.ProtoReflect.Descriptor instead.
func (*ListSecretsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{9}
}

func (x *ListSecretsRequest) GetDataType() DataType {
	if x != nil {
		return x.DataType
	}
	return DataType_DATA_TYPE_UNSPECIFIED
}

func (x *ListSecretsRequest) GetSince() int64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// ListSecretsResponse contains the list of secrets.
type ListSecretsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secrets       []*Secret              `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSecretsResponse) Reset() {
	*x = ListSecretsResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSecretsResponse) ProtoMessage() {}

func (x *ListSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSecretsResponse.ProtoReflect.Descriptor instead.
func (*ListSecretsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{10}
}

func (x *ListSecretsResponse) GetSecrets() []*Secret {
	if x != nil {
		return x.Secrets
	}
	return nil
}

// UpdateSecretRequest contains data for updating a secret.
type UpdateSecretRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EncryptedData   []byte                 `protobuf:"bytes,3,opt,name=encrypted_data,json=encryptedData,proto3" json:"encrypted_data,omitempty"`
	Metadata        string                 `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,5,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"` // For optimistic locking
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateSecretRequest) Reset() {
	*x = UpdateSecretRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretRequest) ProtoMessage() {}

func (x *UpdateSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSecretRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateSecretRequest) GetEncryptedData() []byte {
	if x != nil {
		return x.EncryptedData
	}
	return nil
}

func (x *UpdateSecretRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UpdateSecretRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

// UpdateSecretResponse contains the updated secret.
type UpdateSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        *Secret                `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSecretResponse) Reset() {
	*x = UpdateSecretResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecretResponse) ProtoMessage() {}

func (x *UpdateSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecretResponse.ProtoReflect.Descriptor instead.
func (*UpdateSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateSecretResponse) GetSecret() *Secret {
	if x != nil {
		return x.Secret
	}
	return nil
}

// DeleteSecretRequest contains the secret ID to delete.
type DeleteSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretRequest) Reset() {
	*x = DeleteSecretRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretRequest) ProtoMessage() {}

func (x *DeleteSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretRequest.ProtoReflect.Descriptor instead.
func (*DeleteSecretRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSecretRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteSecretResponse is empty on success.
type DeleteSecretResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSecretResponse) Reset() {
	*x = DeleteSecretResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSecretResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSecretResponse) ProtoMessage() {}

func (x *DeleteSecretResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSecretResponse.ProtoReflect.Descriptor instead.
func (*DeleteSecretResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{14}
}

// SyncRequest contains the client's sync state.
type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTime  int64                  `protobuf:"varint,1,opt,name=last_sync_time,json=lastSyncTime,proto3" json:"last_sync_time,omitempty"` // Unix timestamp of last sync
	LocalChanges  []*Secret              `protobuf:"bytes,2,rep,name=local_changes,json=localChanges,proto3" json:"local_changes,omitempty"`    // Secrets changed on client since last sync
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{15}
}

func (x *SyncRequest) GetLastSyncTime() int64 {
	if x != nil {
		return x.LastSyncTime
	}
	return 0
}

func (x *SyncRequest) GetLocalChanges() []*Secret {
	if x != nil {
		return x.LocalChanges
	}
	return nil
}

func (x *SyncRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

// SyncResponse contains the server's response to sync.
type SyncResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UpdatedSecrets []*Secret              `protobuf:"bytes,1,rep,name=updated_secrets,json=updatedSecrets,proto3" json:"updated_secrets,omitempty"` // Secrets to update on client
	DeletedIds     []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`             // IDs of secrets deleted on server
	ServerTime     int64                  `protobuf:"varint,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`            // Current server time (for next sync)
	HasConflicts   bool                   `protobuf:"varint,4,opt,name=has_conflicts,json=hasConflicts,proto3" json:"has_conflicts,omitempty"`      // Whether there were conflicts
	Conflicts      []*SyncConflict        `protobuf:"bytes,5,rep,name=conflicts,proto3" json:"conflicts,omitempty"`                                 // Detailed conflict info
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{16}
}

func (x *SyncResponse) GetUpdatedSecrets() []*Secret {
	if x != nil {
		return x.UpdatedSecrets
	}
	return nil
}

func (x *SyncResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *SyncResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *SyncResponse) GetHasConflicts() bool {
	if x != nil {
		return x.HasConflicts
	}
	return false
}

func (x *SyncResponse) GetConflicts() []*SyncConflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

// SyncConflict represents a conflict between client and server versions.
type SyncConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SecretId      string                 `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	ClientVersion *Secret                `protobuf:"bytes,2,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ServerVersion *Secret                `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncConflict) Reset() {
	*x = SyncConflict{}
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConflict) ProtoMessage() {}

func (x *SyncConflict) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_gophkeeper_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConflict.ProtoReflect.Descriptor instead.
func (*SyncConflict) Descriptor() ([]byte, []int) {
	return file_pkg_proto_gophkeeper_proto_rawDescGZIP(), []int{17}
}

func (x *SyncConflict) GetSecretId() string {
	if x != nil {
		return x.SecretId
	}
	return ""
}

func (x *SyncConflict) GetClientVersion() *Secret {
	if x != nil {
		return x.ClientVersion
	}
	return nil
}

func (x *SyncConflict) GetServerVersion() *Secret {
	if x != nil {
		return x.ServerVersion
	}
	return nil
}

var File_pkg_proto_gophkeeper_proto protoreflect.FileDescriptor

const file_pkg_proto_gophkeeper_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/gophkeeper.proto\x12\n" +
	"gophkeeper\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"]\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"\xad\x02\n" +
	"\x06Secret\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x121\n" +
	"\tdata_type\x18\x04 \x01(\x0e2\x14.gophkeeper.DataTypeR\bdataType\x12%\n" +
	"\x0eencrypted_data\x18\x05 \x01(\fR\rencryptedData\x12\x1a\n" +
	"\bmetadata\x18\x06 \x01(\tR\bmetadata\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\x12\x18\n" +
	"\adeleted\x18\n" +
	" \x01(\bR\adeleted\"\x9f\x01\n" +
	"\x13CreateSecretRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\tdata_type\x18\x02 \x01(\x0e2\x14.gophkeeper.DataTypeR\bdataType\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"B\n" +
	"\x14CreateSecretResponse\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"\"\n" +
	"\x10GetSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x11GetSecretResponse\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"]\n" +
	"\x12ListSecretsRequest\x121\n" +
	"\tdata_type\x18\x01 \x01(\x0e2\x14.gophkeeper.DataTypeR\bdataType\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x03R\x05since\"C\n" +
	"\x13ListSecretsResponse\x12,\n" +
	"\asecrets\x18\x01 \x03(\v2\x12.gophkeeper.SecretR\asecrets\"\xa7\x01\n" +
	"\x13UpdateSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12%\n" +
	"\x0eencrypted_data\x18\x03 \x01(\fR\rencryptedData\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12)\n" +
	"\x10expected_version\x18\x05 \x01(\x03R\x0fexpectedVersion\"B\n" +
	"\x14UpdateSecretResponse\x12*\n" +
	"\x06secret\x18\x01 \x01(\v2\x12.gophkeeper.SecretR\x06secret\"%\n" +
	"\x13DeleteSecretRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14DeleteSecretResponse\"\x93\x01\n" +
	"\vSyncRequest\x12$\n" +
	"\x0elast_sync_time\x18\x01 \x01(\x03R\flastSyncTime\x127\n" +
	"\rlocal_changes\x18\x02 \x03(\v2\x12.gophkeeper.SecretR\flocalChanges\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\"\xea\x01\n" +
	"\fSyncResponse\x12;\n" +
	"\x0fupdated_secrets\x18\x01 \x03(\v2\x12.gophkeeper.SecretR\x0eupdatedSecrets\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\x03R\n" +
	"serverTime\x12#\n" +
	"\rhas_conflicts\x18\x04 \x01(\bR\fhasConflicts\x126\n" +
	"\tconflicts\x18\x05 \x03(\v2\x18.gophkeeper.SyncConflictR\tconflicts\"\xa1\x01\n" +
	"\fSyncConflict\x12\x1b\n" +
	"\tsecret_id\x18\x01 \x01(\tR\bsecretId\x129\n" +
	"\x0eclient_version\x18\x02 \x01(\v2\x12.gophkeeper.SecretR\rclientVersion\x129\n" +
	"\x0eserver_version\x18\x03 \x01(\v2\x12.gophkeeper.SecretR\rserverVersion*\x81\x01\n" +
	"\bDataType\x12\x19\n" +
	"\x15DATA_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18DATA_TYPE_LOGIN_PASSWORD\x10\x01\x12\x12\n" +
	"\x0eDATA_TYPE_TEXT\x10\x02\x12\x14\n" +
	"\x10DATA_TYPE_BINARY\x10\x03\x12\x12\n" +
	"\x0eDATA_TYPE_CARD\x10\x042\xdf\x04\n" +
	"\n" +
	"GophKeeper\x12E\n" +
	"\bRegister\x12\x1b.gophkeeper.RegisterRequest\x1a\x1c.gophkeeper.RegisterResponse\x12<\n" +
	"\x05Login\x12\x18.gophkeeper.LoginRequest\x1a\x19.gophkeeper.LoginResponse\x12Q\n" +
	"\fCreateSecret\x12\x1f.gophkeeper.CreateSecretRequest\x1a .gophkeeper.CreateSecretResponse\x12H\n" +
	"\tGetSecret\x12\x1c.gophkeeper.GetSecretRequest\x1a\x1d.gophkeeper.GetSecretResponse\x12N\n" +
	"\vListSecrets\x12\x1e.gophkeeper.ListSecretsRequest\x1a\x1f.gophkeeper.ListSecretsResponse\x12Q\n" +
	"\fUpdateSecret\x12\x1f.gophkeeper.UpdateSecretRequest\x1a .gophkeeper.UpdateSecretResponse\x12Q\n" +
	"\fDeleteSecret\x12\x1f.gophkeeper.DeleteSecretRequest\x1a .gophkeeper.DeleteSecretResponse\x129\n" +
	"\x04Sync\x12\x17.gophkeeper.SyncRequest\x1a\x18.gophkeeper.SyncResponseB0Z.github.com/shuklarituparn/gophkeeper/pkg/protob\x06proto3"

var (
	file_pkg_proto_gophkeeper_proto_rawDescOnce sync.Once
	file_pkg_proto_gophkeeper_proto_rawDescData []byte
)

func file_pkg_proto_gophkeeper_proto_rawDescGZIP() []byte {
	file_pkg_proto_gophkeeper_proto_rawDescOnce.Do(func() {
		file_pkg_proto_gophkeeper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_gophkeeper_proto_rawDesc), len(file_pkg_proto_gophkeeper_proto_rawDesc)))
	})
	return file_pkg_proto_gophkeeper_proto_rawDescData
}

var file_pkg_proto_gophkeeper_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_gophkeeper_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_pkg_proto_gophkeeper_proto_goTypes = []any{
	(DataType)(0),                // 0: gophkeeper.DataType
	(*RegisterRequest)(nil),      // 1: gophkeeper.RegisterRequest
	(*RegisterResponse)(nil),     // 2: gophkeeper.RegisterResponse
	(*LoginRequest)(nil),         // 3: gophkeeper.LoginRequest
	(*LoginResponse)(nil),        // 4: gophkeeper.LoginResponse
	(*Secret)(nil),               // 5: gophkeeper.Secret
	(*CreateSecretRequest)(nil),  // 6: gophkeeper.CreateSecretRequest
	(*CreateSecretResponse)(nil), // 7: gophkeeper.CreateSecretResponse
	(*GetSecretRequest)(nil),     // 8: gophkeeper.GetSecretRequest
	(*GetSecretResponse)(nil),    // 9: gophkeeper.GetSecretResponse
	(*ListSecretsRequest)(nil),   // 10: gophkeeper.ListSecretsRequest
	(*ListSecretsResponse)(nil),  // 11: gophkeeper.ListSecretsResponse
	(*UpdateSecretRequest)(nil),  // 12: gophkeeper.UpdateSecretRequest
	(*UpdateSecretResponse)(nil), // 13: gophkeeper.UpdateSecretResponse
	(*DeleteSecretRequest)(nil),  // 14: gophkeeper.DeleteSecretRequest
	(*DeleteSecretResponse)(nil), // 15: gophkeeper.DeleteSecretResponse
	(*SyncRequest)(nil),          // 16: gophkeeper.SyncRequest
	(*SyncResponse)(nil),         // 17: gophkeeper.SyncResponse
	(*SyncConflict)(nil),         // 18: gophkeeper.SyncConflict
}
var file_pkg_proto_gophkeeper_proto_depIdxs = []int32{
	0,  // 0: gophkeeper.Secret.data_type:type_name -> gophkeeper.DataType
	0,  // 1: gophkeeper.CreateSecretRequest.data_type:type_name -> gophkeeper.DataType
	5,  // 2: gophkeeper.CreateSecretResponse.secret:type_name -> gophkeeper.Secret
	5,  // 3: gophkeeper.GetSecretResponse.secret:type_name -> gophkeeper.Secret
	0,  // 4: gophkeeper.ListSecretsRequest.data_type:type_name -> gophkeeper.DataType
	5,  // 5: gophkeeper.ListSecretsResponse.secrets:type_name -> gophkeeper.Secret
	5,  // 6: gophkeeper.UpdateSecretResponse.secret:type_name -> gophkeeper.Secret
	5,  // 7: gophkeeper.SyncRequest.local_changes:type_name -> gophkeeper.Secret
	5,  // 8: gophkeeper.SyncResponse.updated_secrets:type_name -> gophkeeper.Secret
	18, // 9: gophkeeper.SyncResponse.conflicts:type_name -> gophkeeper.SyncConflict
	5,  // 10: gophkeeper.SyncConflict.client_version:type_name -> gophkeeper.Secret
	5,  // 11: gophkeeper.SyncConflict.server_version:type_name -> gophkeeper.Secret
	1,  // 12: gophkeeper.GophKeeper.Register:input_type -> gophkeeper.RegisterRequest
	3,  // 13: gophkeeper.GophKeeper.Login:input_type -> gophkeeper.LoginRequest
	6,  // 14: gophkeeper.GophKeeper.CreateSecret:input_type -> gophkeeper.CreateSecretRequest
	8,  // 15: gophkeeper.GophKeeper.GetSecret:input_type -> gophkeeper.GetSecretRequest
	10, // 16: gophkeeper.GophKeeper.ListSecrets:input_type -> gophkeeper.ListSecretsRequest
	12, // 17: gophkeeper.GophKeeper.UpdateSecret:input_type -> gophkeeper.UpdateSecretRequest
	14, // 18: gophkeeper.GophKeeper.DeleteSecret:input_type -> gophkeeper.DeleteSecretRequest
	16, // 19: gophkeeper.GophKeeper.Sync:input_type -> gophkeeper.SyncRequest
	2,  // 20: gophkeeper.GophKeeper.Register:output_type -> gophkeeper.RegisterResponse
	4,  // 21: gophkeeper.GophKeeper.Login:output_type -> gophkeeper.LoginResponse
	7,  // 22: gophkeeper.GophKeeper.CreateSecret:output_type -> gophkeeper.CreateSecretResponse
	9,  // 23: gophkeeper.GophKeeper.GetSecret:output_type -> gophkeeper.GetSecretResponse
	11, // 24: gophkeeper.GophKeeper.ListSecrets:output_type -> gophkeeper.ListSecretsResponse
	13, // 25: gophkeeper.GophKeeper.UpdateSecret:output_type -> gophkeeper.UpdateSecretResponse
	15, // 26: gophkeeper.GophKeeper.DeleteSecret:output_type -> gophkeeper.DeleteSecretResponse
	17, // 27: gophkeeper.GophKeeper.Sync:output_type -> gophkeeper.SyncResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_proto_gophkeeper_proto_init() }
func file_pkg_proto_gophkeeper_proto_init() {
	if File_pkg_proto_gophkeeper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_gophkeeper_proto_rawDesc), len(file_pkg_proto_gophkeeper_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_gophkeeper_proto_goTypes,
		DependencyIndexes: file_pkg_proto_gophkeeper_proto_depIdxs,
		EnumInfos:         file_pkg_proto_gophkeeper_proto_enumTypes,
		MessageInfos:      file_pkg_proto_gophkeeper_proto_msgTypes,
	}.Build()
	File_pkg_proto_gophkeeper_proto = out.File
	file_pkg_proto_gophkeeper_proto_goTypes = nil
	file_pkg_proto_gophkeeper_proto_depIdxs = nil
}
